# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 240)
        MainWindow.setMinimumSize(QtCore.QSize(960, 240))
        MainWindow.setMaximumSize(QtCore.QSize(960, 240))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{ background: rgb(26,27,32) }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(960, 240))
        self.centralwidget.setObjectName("centralwidget")
        self.record_button = QtWidgets.QPushButton(self.centralwidget)
        self.record_button.setGeometry(QtCore.QRect(90, 20, 124, 158))
        self.record_button.setMaximumSize(QtCore.QSize(200, 200))
        self.record_button.setBaseSize(QtCore.QSize(200, 200))
        self.record_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.record_button.setMouseTracking(True)
        self.record_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.record_button.setStyleSheet("#record_button{\n"
"background-image:url(:/imgs/F:/py_pro/opr-record-pc/ui/assets/record_normal_66x66.png);\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"background-color:transparent;\n"
"color:rgb(2,124,248);\n"
"font-size:20px;\n"
"font-family:Microsoft Yahei;\n"
"text-align:bottom;\n"
"}\n"
"#record_button:hover{\n"
"background-image:url(:/imgs/F:/py_pro/opr-record-pc/ui/assets/record_hover_66x66.png);\n"
"color:rgb(22,164,248);\n"
"}")
        self.record_button.setObjectName("record_button")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(280, 20, 124, 158))
        self.play_button.setMaximumSize(QtCore.QSize(200, 200))
        self.play_button.setBaseSize(QtCore.QSize(200, 200))
        self.play_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_button.setMouseTracking(True)
        self.play_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.play_button.setStyleSheet("#play_button{\n"
"background-image:url(:/imgs/F:/py_pro/opr-record-pc/ui/assets/play_normal_66x66.png);\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"background-color:transparent;\n"
"color:rgb(2,124,248);\n"
"font-size:20px;\n"
"font-family:Microsoft Yahei;\n"
"text-align:bottom;\n"
"}\n"
"#play_button:hover{\n"
"background-image:url(:/imgs/F:/py_pro/opr-record-pc/ui/assets/play_hover_66x66.png);\n"
"color:rgb(22,164,248);\n"
"}")
        self.play_button.setObjectName("play_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("#QStatusBar{ background: rgb(26,27,32) }")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.record_button.setText(_translate("MainWindow", "录制项目"))
        self.play_button.setText(_translate("MainWindow", "播放项目"))
import test_rc
